### ISSUE TITLE
You make third-party requests

### ISSUE THREAD

**Issue by blobgo** [micahflee/onionshare-website#11]
In your Readme you state:
> * There aren't any third party resources included. When someone visits https://onionshare.org/, their browser shouldn't make any requests to any other domain names (including Google to load fonts, jquery, etc.).

However you violate your own principle with this Piwik tracking:
![onionsharetraffic](https://cloud.githubusercontent.com/assets/12105354/12075576/3f574978-b17d-11e5-82d4-2ee8d77b3485.PNG)

**Comment by micahflee** [comment]
`piwik.micahflee.com` is a first party request, since I control both domains (and in fact they're both on the same server, both share the same SSL certficate, etc.). But that said, I don't actually ever look at the analytics, so I decided to go ahead and remove it.

**Comment by blobgo** [comment]
Okay. And in your readme you don't talk about "first party" or something like that, but about "other domain names". And `piwik.micahflee.com <> onionshare.org` :wink:
