### ISSUE TITLE
Wrong character encoding

### ISSUE THREAD

**Issue by LaxrMediumWas** [micahflee/onionshare-website#12]
![screenshot](https://cloud.githubusercontent.com/assets/13087157/12111122/f785180e-b3a3-11e5-8e95-fac64d811b31.gif)

**Comment by micahflee** [comment]
This is the wrong git repository. You opened this bug on the onionshare-website repo, when you probably meant the onionshare repo: https://github.com/micahflee/onionshare

That said, this issue probably will be gone in the next release of onionshare. It has been ported to python3, so all of the encoding stuff is improved.
